name: Build Debian Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Debian-based Docker image for ${{ matrix.architecture }}
      run: |
        docker buildx build --file docker/debian/Dockerfile \
          --platform linux/${{ matrix.architecture }} \
          --tag my-php-image:fpm-${{ matrix.architecture }} --push .

    - name: Push Debian Docker image to Docker Hub for ${{ matrix.architecture }}
      run: |
        docker tag my-php-image:fpm-${{ matrix.architecture }} username/my-php-image:fpm-${{ matrix.architecture }}
        docker push username/my-php-image:fpm-${{ matrix.architecture }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
