name: Build Debian Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Debian-based Docker image for ${{ matrix.architecture }}
      id: build-debian
      run: |
        docker buildx build --file docker/debian/Dockerfile \
          --platform linux/${{ matrix.architecture }} \
          --tag imashen/php:8.3.8-fpm --push .

    - name: Create and push multi-architecture manifest for Debian
      if: ${{ matrix.architecture == 'arm64' }}
      run: |
        docker manifest create imashen/php:8.3.8-fpm \
          --amend imashen/php:8.3.8-fpm-amd64 \
          --amend imashen/php:8.3.8-fpm-arm64
        docker manifest push imashen/php:8.3.8-fpm
